### ISSUE TITLE
duplication

### ISSUE THREAD

**Issue by aric87** [profzoidberg/ratings-investigator#10]
Here; https://github.com/rlynn523/ratings-investigator/blob/master/js/app.js#L9
and 
here: https://github.com/rlynn523/ratings-investigator/blob/master/js/app.js#L14

You're clearing the value. Should be able to remove line 9, and get the same effect

**Comment by rlynn523** [comment]
removed line 9

**Comment by rlynn523** [comment]
removed line 9
