### ISSUE TITLE
button styles

### ISSUE THREAD

**Issue by aric87** [profzoidberg/ratings-investigator#8]
It's pretty uncommon to use the "old school" button design with the border set as it is. That's up to you, but, you should add some padding to them to make the text in the button easier to read. 
Since the background is a bit dark, and the font is thin, the larger button is easier on the eyes. Also, you might consider changing the :focus color to something that doesn't match the background. That's more of an accessability to concern, but, if you're using keyboard navigation, it's hard to know where you're focusing

<img width="382" alt="screen shot 2016-09-20 at 9 28 29 am" src="https://cloud.githubusercontent.com/assets/9463572/18672080/a28f8306-7f14-11e6-8559-911ca5ee2b46.png">

**Comment by rlynn523** [comment]
updated the button and input stylings to material design
